### ISSUE TITLE
Très intéressant.

### ISSUE THREAD

**Issue by saponace** [jarnault/sopraDevops#1]
Je trouve ce repo très interessant. Plein de surprises et de commits palpitants.
beau travail.

**Comment by jarnault** [comment]
![saponace](https://cloud.githubusercontent.com/assets/10628755/14638260/de1865d4-0636-11e6-86c2-e8548c16684d.PNG)

heureusement que j'avais linké mon Slack !

**Comment by saponace** [comment]
Hahaha, desole, j'ai pas pu men empecher qund j'ai vu ca sur ma page d'accueil
Ca va ton stage toi sinon ?
